name: ymuse
base: core20
adopt-info: ymuse
summary: Easy, functional, and snappy client for Music Player Daemon
title: Ymuse
description: |
  Ymuse is a simple and quick client for the Music Player Daemon (MPD)
  using the GTK toolkit. It supports play queue management and
  filtering, music library browsing and search, Internet streams, and
  provides broad customisation possibilities.

icon: resources/icons/hicolor/scalable/apps/icon.svg
license: Apache-2.0
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  ymuse:
    desktop: ymuse.desktop
    command: ymuse
    extensions:
      - gnome-3-28
    plugs:
      - network
    slots:
      - dbus-daemon

parts:
  ymuse:
    plugin: go
    source: .
    build-packages:
      - git
      - gcc
      - gettext

    override-pull: |
      snapcraftctl pull

      # Use version from git
      version="$(git describe --always --tags)"
      snapcraftctl set-version "$version"
      snapcraftctl set-grade "$(echo $version | grep -q '-' && echo devel || echo stable)"

    override-build: |
      set -eu
      go generate
      go build -ldflags "-s -w -X main.version=$(git describe --always --tags) -X main.commit=$(git rev-parse HEAD) -X main.date=$(date --iso-8601=seconds)" -o "${SNAPCRAFT_PART_INSTALL}"

  resources:
    plugin: dump
    source: resources/
    organize:
      icons: usr/share/icons
      i18n/generated: usr/share/locale
    prime:
      - usr/
      - ymuse.desktop

    override-pull: |
      snapcraftctl pull

      # Fix icon path in the .desktop
      sed -i -E 's!^Icon=.*!Icon=/usr/share/icons/hicolor/scalable/apps/icon.svg!' ymuse.desktop

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.yktoo.ymuse
