name: Go

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev xvfb gettext

    - name: Prepare
      run: |
        go generate
        go mod download

    - name: Verify format
      run: test `gofmt -l . | wc -l` = 0

    - name: Test
      run: |
        export DISPLAY=:99.0
        sudo /usr/bin/Xvfb $DISPLAY &>/dev/null &
        go test -v ./...

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Verify GoReleaser config
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: check

      - name: Build and deploy (dry run)
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist
